
/* Drop Foreign Key Constraints */

USE [wizzio]
GO


IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_PROCESS_ID]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [PROCESS_IMAGES] DROP CONSTRAINT [FK_PROCESS_ID]
GO

/* Drop Tables */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PROCESS_DETAILS]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PROCESS_DETAILS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[PROCESS_IMAGES]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [PROCESS_IMAGES]
GO


/* Create Tables */

CREATE TABLE [PROCESS_DETAILS]
(
	[PROCESS_ID] bigint NOT NULL IDENTITY (1, 1),
	[NIF] nvarchar(9) NOT NULL,
	[NAME] nvarchar(300) NOT NULL,
	[EMAIL] nvarchar(300) NULL,
	[ID_NUMBER] nvarchar(9) NOT NULL,
	[PHONE_NUMBER] nvarchar(15) NOT NULL,
	[CREATION_USER] nvarchar(50) NOT NULL,
	[CREATION_DATE] DATETIME,
	[UPDATE_USER] nvarchar(50) NOT NULL,
	[UPDATE_DATE] DATETIME
	
)
GO


CREATE TABLE [PROCESS_IMAGES]
(
	[IMAGE_ID] bigint NOT NULL IDENTITY (1, 1),
	[PROCESS_ID] bigint NOT NULL,
	[IMAGE_TYPE] nvarchar(50) NOT NULL,
	[BASE64] VARCHAR(MAX) NOT NULL,
	[CREATION_USER] nvarchar(50) NOT NULL,
	[CREATION_DATE] DATETIME,
	[UPDATE_USER] nvarchar(50) NOT NULL,
	[UPDATE_DATE] DATETIME
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [PROCESS_DETAILS] 
 ADD CONSTRAINT [PK_PROCESS_DETAILS]
	PRIMARY KEY CLUSTERED ([PROCESS_ID])
GO

ALTER TABLE [PROCESS_IMAGES] 
 ADD CONSTRAINT [PK_PROCESS_IMAGES]
	PRIMARY KEY CLUSTERED ([IMAGE_ID])
GO

/* Create Foreign Key Constraints */

ALTER TABLE [PROCESS_IMAGES] ADD CONSTRAINT [FK_PROCESS_IMAGES_PROCESS_DETAILS]
	FOREIGN KEY ([PROCESS_ID]) REFERENCES [PROCESS_DETAILS] ([PROCESS_ID]) ON DELETE No Action ON UPDATE No Action
GO

